CREATE DEFINER=`accnaust_ACCN`@`101.189.80.166` PROCEDURE `GetUserID`(Name VARCHAR(20), IP VARCHAR(16))
BEGIN
	SELECT U.ID
	FROM User U
	WHERE TRIM(LOWER(U.Name)) = TRIM(LOWER(Name)) 
    AND TRIM(U.IP) = TRIM(IP);
END