CREATE DEFINER=`accnaust_ACCN`@`101.185.215.189` PROCEDURE `UserExists`(Name VARCHAR(20), IP VARCHAR(16))
BEGIN
	SELECT U.ID
	FROM User U
	WHERE TRIM(LOWER(U.Name)) = TRIM(LOWER(Name)) AND TRIM(U.IP) = TRIM(IP);
END